export const Projects = [
  {
    name: "Mr. Rajesh Yadav",
    add: "Pardesipura,Indore",
    area: "3152",
    floor: "G + 2",
    cost: "54.5 Laks",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
    photoGallery: [
      "/assets/02_Project.png",
      "/assets/02_Project.png",
      "/assets/02_Project.png"
    ]
  },
  {
    name: "Mr. Vinay Pingle Residence",
    add: "Andanva,Prayagraj",
    area: "3023",
    floor: "G + 1",
    cost: "52.3 Laks",
    url: "/assets/01_Project.png",
    months: "7.5",
    rating: "4.8",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mr. Priyansh Joshi's",
    add: "Naini,Prayagraj",
    area: "2854",
    floor: "G + 1",
    cost: "65.4 Lakhs",
    url: "/assets/01_Project.png",
    months: "7.5",
    rating: "4.6",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mr. Rajesh Sahu",
    add: "Lalghati,Bhopal",
    area: "3794",
    floor: "G + 2",
    cost: "54.28 Lakhs",
    url: "/assets/Aashu.png",
    months: "11",
    rating: "4.6",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "https://www.youtube.com/embed/lg7bE3lPVG0",
  },
  {
    name: "Mr. Wadhvani Residence",
    add: "Bengali Square,Indore",
    area: "1750",
    floor: "G + 1",
    cost: "28.9 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Akshat Apartment",
    add: "Ashoka Garden,Bhopal",
    area: "12160",
    floor: "G + 4",
    cost: "158.42 Lakhs",
    url: "/assets/01_Project.png",
    months: "14",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mr. Mahesh Sahu",
    add: "Lalghati,Bhopal",
    area: "3550",
    floor: "G + 2",
    cost: "57.6 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mr. Praveen Villa",
    add: "RK Puram,Prayagraj",
    area: "2850",
    floor: "G + 1",
    cost: "48.6 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mrs Geeta Residence",
    add: "Lalghati,Bhopal",
    area: "3554",
    floor: "G + 2",
    cost: "54.10 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mr. Akshat Kanasal",
    add: "Bhawarkua,Indore",
    area: "2505",
    floor: "G + 1",
    cost: "48.6 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `    `,
    about: ``,
    videourl: "",
  },
  {
    name: "Mr & Mrs Sahu Residence",
    add: "Nayapura,Bhopal",
    area: "2700",
    floor: "G + 2",
    cost: "40.10 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: ``,
    about: ``,
    videourl: "",
  },
  {
    name: "Grace Garden Housing",
    add: "BHEL,Bhopal",
    area: "1200",
    floor: "G + 1",
    cost: "66.20 Lakhs",
    url: "/assets/01_Project.png",
    months: "9.5",
    rating: "4.5",
    contractorName: "KONNBOT Team",
    constructorData: `   `,
    about: ``,
    videourl: "https://www.youtube.com/embed/k7vAqPTVKjY",
  },
];
