export const Blogs = [
  {
    title:
      "White Space Creating Ambiance with minimal Boxing & Louvers makes the Elevation more.",
    url: "/assets/01_HomePage.png",
    blog: `The Indus Valley Civilization covered a large area around the Indus River basin and beyond in late Bronze Age India. In its mature phase, from about 2600 to 1900 BCE, it produced several cities marked by great uniformity within and between sites, including Harappa, Lothal, and the UNESCO World Heritage Site Mohenjo-daro. The civic and town planning and engineering aspects of these are remarkable, but the design of the buildings is "of a startling utilitarian character". There are granaries, drains, lombadthing, water-courses and tanks, but neither palaces nor temples have been identified, though cities have a central raised and fortified "citadel".[2] Mohenjo-daro has wells which may be the predecessors of the stepwell.[3] As many as 700 wells have been discovered in just one section of the city, leading scholars to believe that 'cylindrical brick lined wells' were invented by the Indus Valley Civilization.[3]

    Architectural decoration is extremely minimal, though there are "narrow pointed niches" inside some buildings. Most of the art found is in miniature forms like seals, and mainly in terracotta, but there are very few larger sculptures of figures. In most sites fired mud-brick (not sun-baked as in Mesopotamia) is used exclusively as the building material, but a few such as Dholavira are in stone. Most houses have two storeys, and very uniform sizes and plans. The large cities declined relatively quickly, for unknown reasons, leaving a less sophisticated village culture behind.[4]
    
    600 BCE—250 CE
    
    After the Indus Valley Civilization, there are few traces of Indian architecture, which probably mostly used wood, or brick which has been recycled, until around the time of the Maurya Empire, from 322 to 185 BCE. From this period for several centuries onwards, much the best remains are of Indian rock-cut architecture, mostly Buddhist, and there are also a number of Buddhist images that give very useful information.
    
    Buddhist construction of monastic buildings apparently begins before the death of Buddha, probably around 400 BCE.[5] This first generation only survives in floor-plans, notably at the Jivakarama vihara in Bihar.
    
    Walled and moated cities with large gates and multi-storied buildings which consistently used chaitya arches, no doubt in wood, for roofs and upper structures above more solid storeys are important features of the architecture during this period. The reliefs of Sanchi, dated to the 1st centuries BCE-CE, show cities such as Kushinagar or Rajagriha as splendid walled cities, as in the Royal cortege leaving Rajagriha or War over the Buddha's relics. These views of ancient Indian cities have been relied on for the understanding of ancient Indian urban architecture.[6]
    
    In the case of the Mauryan capital Pataliputra (near Patna), we have Greek accounts, and that of Faxian; Megasthenes (a visitor around 300 BCE) mentions 564 towers and 64 gates in the city walls. Modern excavations have uncovered a "massive palisade of teak beams held together with iron dowels".[7] A huge apadana-like hall with eighty sandstone columns shows clear influence from contemporary Achaemenid Persia.[8] The single massive sandstone Pataliputra capital shows clear Hellenistic features, reaching India via Persia.[9] The famous Ashoka columns show great sophistication, and a variety of influences in their details. In both these cases a now-vanished Indian predecessor tradition in wood is likely.[10]
    
    Gupta Architecture
    
    For reasons that are not entirely clear, for the most part the Gupta period represented a hiatus in Indian rock-cut architecture, with the first wave of construction finishing before the empire was assembled, and the second wave beginning in the late 5th century, after it ended. This is the case, for example, at the Ajanta Caves, with an early group made by 220 CE at the latest, and a later one probably all after about 460.[19] Instead, the period has left almost the first surviving free-standing structures in India, in particular, the beginnings of Hindu temple architecture. As Milo Beach puts it: "Under the Guptas, India was quick to join the rest of the medieval world in a passion for housing precious objects in stylized architectural frameworks",[20] the "precious objects" being primarily the icons of gods.
    
    The most famous remaining monuments in a broadly Gupta style, the caves at Ajanta, Elephanta, and Ellora (respectively Buddhist, Hindu, and mixed including Jain) were in fact produced under other dynasties in Central India, and in the case of Ellora after the Gupta period, but primarily reflect the monumentality and balance of Guptan style. Ajanta contains by far the most significant survivals of painting from this and the surrounding periods, showing a mature form which had probably had a long development, mainly in painting palaces.[21] The Hindu Udayagiri Caves actually record connections with the dynasty and its ministers,[22] and the Dashavatara Temple at Deogarh is a major temple, one of the earliest to survive, with important sculpture.[23]
    
    Examples of early North Indian Hindu temples that have survived after the Udayagiri Caves in Madhya Pradesh include those at Tigawa (early 5th century),[24] Sanchi Temple 17 (similar, but respectively Hindu and Buddhist), Deogarh, Parvati Temple, Nachna (465),[25] Bhitargaon, the largest Gupta brick temple to survive,[26] and Lakshman Brick Temple, Sirpur (600–625 CE). Gop Temple in Gujarat (c. 550 or later) is an oddity, with no surviving close comparator.[27]
    
    There are a number of different broad models, which would continue to be the case for more than a century after the Gupta period, but temples such as Tigawa and Sanchi Temple 17, which are small but massively built stone prostyle buildings with a sanctuary and a columned porch, show the most common basic plan that continues today. Both of these have flat roofs over the sanctuary, which would become uncommon by about the 8th century. The Mahabodhi Temple, Bhitargaon, Deogarh and Gop already all show high superstructures of different shapes.[28] The Chejarla Kapoteswara temple demonstrates that free-standing chaitya-hall temples with barrel roofs continued to be built, probably with many smaller examples in wood.[29]`,
  },
  {
    title:
      "White Space Creating Ambiance with minimal Boxing & Louvers makes the Elevation more.",
    url: "/assets/01_HomePage.png",
    blog: `The Indus Valley Civilization covered a large area around the Indus River basin and beyond in late Bronze Age India. In its mature phase, from about 2600 to 1900 BCE, it produced several cities marked by great uniformity within and between sites, including Harappa, Lothal, and the UNESCO World Heritage Site Mohenjo-daro. The civic and town planning and engineering aspects of these are remarkable, but the design of the buildings is "of a startling utilitarian character". There are granaries, drains, lombadthing, water-courses and tanks, but neither palaces nor temples have been identified, though cities have a central raised and fortified "citadel".[2] Mohenjo-daro has wells which may be the predecessors of the stepwell.[3] As many as 700 wells have been discovered in just one section of the city, leading scholars to believe that 'cylindrical brick lined wells' were invented by the Indus Valley Civilization.[3]

    Architectural decoration is extremely minimal, though there are "narrow pointed niches" inside some buildings. Most of the art found is in miniature forms like seals, and mainly in terracotta, but there are very few larger sculptures of figures. In most sites fired mud-brick (not sun-baked as in Mesopotamia) is used exclusively as the building material, but a few such as Dholavira are in stone. Most houses have two storeys, and very uniform sizes and plans. The large cities declined relatively quickly, for unknown reasons, leaving a less sophisticated village culture behind.[4]
    
    600 BCE—250 CE
    
    After the Indus Valley Civilization, there are few traces of Indian architecture, which probably mostly used wood, or brick which has been recycled, until around the time of the Maurya Empire, from 322 to 185 BCE. From this period for several centuries onwards, much the best remains are of Indian rock-cut architecture, mostly Buddhist, and there are also a number of Buddhist images that give very useful information.
    
    Buddhist construction of monastic buildings apparently begins before the death of Buddha, probably around 400 BCE.[5] This first generation only survives in floor-plans, notably at the Jivakarama vihara in Bihar.
    
    Walled and moated cities with large gates and multi-storied buildings which consistently used chaitya arches, no doubt in wood, for roofs and upper structures above more solid storeys are important features of the architecture during this period. The reliefs of Sanchi, dated to the 1st centuries BCE-CE, show cities such as Kushinagar or Rajagriha as splendid walled cities, as in the Royal cortege leaving Rajagriha or War over the Buddha's relics. These views of ancient Indian cities have been relied on for the understanding of ancient Indian urban architecture.[6]
    
    In the case of the Mauryan capital Pataliputra (near Patna), we have Greek accounts, and that of Faxian; Megasthenes (a visitor around 300 BCE) mentions 564 towers and 64 gates in the city walls. Modern excavations have uncovered a "massive palisade of teak beams held together with iron dowels".[7] A huge apadana-like hall with eighty sandstone columns shows clear influence from contemporary Achaemenid Persia.[8] The single massive sandstone Pataliputra capital shows clear Hellenistic features, reaching India via Persia.[9] The famous Ashoka columns show great sophistication, and a variety of influences in their details. In both these cases a now-vanished Indian predecessor tradition in wood is likely.[10]
    
    Gupta Architecture
    
    For reasons that are not entirely clear, for the most part the Gupta period represented a hiatus in Indian rock-cut architecture, with the first wave of construction finishing before the empire was assembled, and the second wave beginning in the late 5th century, after it ended. This is the case, for example, at the Ajanta Caves, with an early group made by 220 CE at the latest, and a later one probably all after about 460.[19] Instead, the period has left almost the first surviving free-standing structures in India, in particular, the beginnings of Hindu temple architecture. As Milo Beach puts it: "Under the Guptas, India was quick to join the rest of the medieval world in a passion for housing precious objects in stylized architectural frameworks",[20] the "precious objects" being primarily the icons of gods.
    
    The most famous remaining monuments in a broadly Gupta style, the caves at Ajanta, Elephanta, and Ellora (respectively Buddhist, Hindu, and mixed including Jain) were in fact produced under other dynasties in Central India, and in the case of Ellora after the Gupta period, but primarily reflect the monumentality and balance of Guptan style. Ajanta contains by far the most significant survivals of painting from this and the surrounding periods, showing a mature form which had probably had a long development, mainly in painting palaces.[21] The Hindu Udayagiri Caves actually record connections with the dynasty and its ministers,[22] and the Dashavatara Temple at Deogarh is a major temple, one of the earliest to survive, with important sculpture.[23]
    
    Examples of early North Indian Hindu temples that have survived after the Udayagiri Caves in Madhya Pradesh include those at Tigawa (early 5th century),[24] Sanchi Temple 17 (similar, but respectively Hindu and Buddhist), Deogarh, Parvati Temple, Nachna (465),[25] Bhitargaon, the largest Gupta brick temple to survive,[26] and Lakshman Brick Temple, Sirpur (600–625 CE). Gop Temple in Gujarat (c. 550 or later) is an oddity, with no surviving close comparator.[27]
    
    There are a number of different broad models, which would continue to be the case for more than a century after the Gupta period, but temples such as Tigawa and Sanchi Temple 17, which are small but massively built stone prostyle buildings with a sanctuary and a columned porch, show the most common basic plan that continues today. Both of these have flat roofs over the sanctuary, which would become uncommon by about the 8th century. The Mahabodhi Temple, Bhitargaon, Deogarh and Gop already all show high superstructures of different shapes.[28] The Chejarla Kapoteswara temple demonstrates that free-standing chaitya-hall temples with barrel roofs continued to be built, probably with many smaller examples in wood.[29]`,
  },
  {
    title:
      "White Space Creating Ambiance with minimal Boxing & Louvers makes the Elevation more.",
    url: "/assets/01_HomePage.png",
    blog: `The Indus Valley Civilization covered a large area around the Indus River basin and beyond in late Bronze Age India. In its mature phase, from about 2600 to 1900 BCE, it produced several cities marked by great uniformity within and between sites, including Harappa, Lothal, and the UNESCO World Heritage Site Mohenjo-daro. The civic and town planning and engineering aspects of these are remarkable, but the design of the buildings is "of a startling utilitarian character". There are granaries, drains, lombadthing, water-courses and tanks, but neither palaces nor temples have been identified, though cities have a central raised and fortified "citadel".[2] Mohenjo-daro has wells which may be the predecessors of the stepwell.[3] As many as 700 wells have been discovered in just one section of the city, leading scholars to believe that 'cylindrical brick lined wells' were invented by the Indus Valley Civilization.[3]

    Architectural decoration is extremely minimal, though there are "narrow pointed niches" inside some buildings. Most of the art found is in miniature forms like seals, and mainly in terracotta, but there are very few larger sculptures of figures. In most sites fired mud-brick (not sun-baked as in Mesopotamia) is used exclusively as the building material, but a few such as Dholavira are in stone. Most houses have two storeys, and very uniform sizes and plans. The large cities declined relatively quickly, for unknown reasons, leaving a less sophisticated village culture behind.[4]
    
    600 BCE—250 CE
    
    After the Indus Valley Civilization, there are few traces of Indian architecture, which probably mostly used wood, or brick which has been recycled, until around the time of the Maurya Empire, from 322 to 185 BCE. From this period for several centuries onwards, much the best remains are of Indian rock-cut architecture, mostly Buddhist, and there are also a number of Buddhist images that give very useful information.
    
    Buddhist construction of monastic buildings apparently begins before the death of Buddha, probably around 400 BCE.[5] This first generation only survives in floor-plans, notably at the Jivakarama vihara in Bihar.
    
    Walled and moated cities with large gates and multi-storied buildings which consistently used chaitya arches, no doubt in wood, for roofs and upper structures above more solid storeys are important features of the architecture during this period. The reliefs of Sanchi, dated to the 1st centuries BCE-CE, show cities such as Kushinagar or Rajagriha as splendid walled cities, as in the Royal cortege leaving Rajagriha or War over the Buddha's relics. These views of ancient Indian cities have been relied on for the understanding of ancient Indian urban architecture.[6]
    
    In the case of the Mauryan capital Pataliputra (near Patna), we have Greek accounts, and that of Faxian; Megasthenes (a visitor around 300 BCE) mentions 564 towers and 64 gates in the city walls. Modern excavations have uncovered a "massive palisade of teak beams held together with iron dowels".[7] A huge apadana-like hall with eighty sandstone columns shows clear influence from contemporary Achaemenid Persia.[8] The single massive sandstone Pataliputra capital shows clear Hellenistic features, reaching India via Persia.[9] The famous Ashoka columns show great sophistication, and a variety of influences in their details. In both these cases a now-vanished Indian predecessor tradition in wood is likely.[10]
    
    Gupta Architecture
    
    For reasons that are not entirely clear, for the most part the Gupta period represented a hiatus in Indian rock-cut architecture, with the first wave of construction finishing before the empire was assembled, and the second wave beginning in the late 5th century, after it ended. This is the case, for example, at the Ajanta Caves, with an early group made by 220 CE at the latest, and a later one probably all after about 460.[19] Instead, the period has left almost the first surviving free-standing structures in India, in particular, the beginnings of Hindu temple architecture. As Milo Beach puts it: "Under the Guptas, India was quick to join the rest of the medieval world in a passion for housing precious objects in stylized architectural frameworks",[20] the "precious objects" being primarily the icons of gods.
    
    The most famous remaining monuments in a broadly Gupta style, the caves at Ajanta, Elephanta, and Ellora (respectively Buddhist, Hindu, and mixed including Jain) were in fact produced under other dynasties in Central India, and in the case of Ellora after the Gupta period, but primarily reflect the monumentality and balance of Guptan style. Ajanta contains by far the most significant survivals of painting from this and the surrounding periods, showing a mature form which had probably had a long development, mainly in painting palaces.[21] The Hindu Udayagiri Caves actually record connections with the dynasty and its ministers,[22] and the Dashavatara Temple at Deogarh is a major temple, one of the earliest to survive, with important sculpture.[23]
    
    Examples of early North Indian Hindu temples that have survived after the Udayagiri Caves in Madhya Pradesh include those at Tigawa (early 5th century),[24] Sanchi Temple 17 (similar, but respectively Hindu and Buddhist), Deogarh, Parvati Temple, Nachna (465),[25] Bhitargaon, the largest Gupta brick temple to survive,[26] and Lakshman Brick Temple, Sirpur (600–625 CE). Gop Temple in Gujarat (c. 550 or later) is an oddity, with no surviving close comparator.[27]
    
    There are a number of different broad models, which would continue to be the case for more than a century after the Gupta period, but temples such as Tigawa and Sanchi Temple 17, which are small but massively built stone prostyle buildings with a sanctuary and a columned porch, show the most common basic plan that continues today. Both of these have flat roofs over the sanctuary, which would become uncommon by about the 8th century. The Mahabodhi Temple, Bhitargaon, Deogarh and Gop already all show high superstructures of different shapes.[28] The Chejarla Kapoteswara temple demonstrates that free-standing chaitya-hall temples with barrel roofs continued to be built, probably with many smaller examples in wood.[29]`,
  },
];
